---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    isfixedip: "true"
    kubernetes.io/hostname: centos2
  labels:
    app: @NAME@
  name: @NAME@
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: @NAME@
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: cbr0
      creationTimestamp: null
      labels:
        app: @NAME@
    spec:
      containers:
      - image: cargo-infra.caicloud.xyz/library/hsocket_python:x0
        imagePullPolicy: IfNotPresent
        name: @NAME@
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: @NAME@
  labels:
    app: @NAME@
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: @NAME@
